### ISSUE TITLE
Client crashing

### ISSUE THREAD

**Issue by kryptongamer** [Globox1997/LevelZ#1]
i got a crash after 5 mins... https://pastebin.com/U3grdRq3

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at net.levelz.stats.PlayerStatsManager.playerLevelisHighEnough(PlayerStatsManager.java:226)
	at net.minecraft.class_1799.handler$bop000$getTooltipMixin(class_1799.java:3924)
	at net.minecraft.class_1799.method_7950(class_1799.java:677)
	at net.minecraft.class_437.method_25408(class_437.java:181)
	at net.minecraft.class_437.method_25409(class_437.java:168)
	at net.minecraft.class_481.method_25409(class_481.java:742)
	at net.minecraft.class_465.method_2380(class_465.java:190)
	at net.minecraft.class_481.method_25394(class_481.java:703)
	at net.minecraft.class_757.method_3192(class_757.java:874)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by Globox1997** [comment]
When does this exactly happen?

**Comment by Globox1997** [comment]
Does it happen while hovering over a specific item/block in an inventory or while mining anything?
Singleplayer or on a server?

**Comment by kryptongamer** [comment]
Server, not cursor, its random idk

**Comment by kryptongamer** [comment]
Well, I've been testing, I don't know if it's an incompatibility, but if I have LevelZ activated I can't use the Flan menu (a claim mod)

**Comment by kryptongamer** [comment]
Trying craft iron shield crash too

**Comment by Globox1997** [comment]
Probably fixed with [https://github.com/Globox1997/LevelZ/commit/7283aba6dcd521de2626506e6805edba51796a5a](https://github.com/Globox1997/LevelZ/commit/7283aba6dcd521de2626506e6805edba51796a5a), please close this issue if it is fixed with mod version 1.0.1

**Comment by kryptongamer** [comment]
working
