### ISSUE TITLE
This do0es not have to do with the mod but I need help figuring out what is wrong

### ISSUE THREAD

**Issue by POH1** [Globox1997/LevelZ#106]
java.lang.RuntimeException: Non-unique Mixin config name mixins.reach-entity-attributes.json used by the mods feudalw and reach-entity-attributes
at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:85)
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Globox1997** [comment]
if you post the full crash log I might can help you
