### ISSUE TITLE
Two major bugs

### ISSUE THREAD

**Issue by divinevtwo** [Globox1997/LevelZ#16]
1. The game crashes when a player has maxed skills and walks over soulsand/soil (this is not related to the agility stat tho)
2. On maxed skills the player occasionally applies Frost Walker to nearby water blocks (No, I'm not using FW on my armor. I believe this is related to the agility stat, not 100% sure tho).

**Comment by Globox1997** [comment]
Could you send a crash log for the first bug and does the second one happen while only levelz is installed?

**Comment by divinevtwo** [comment]
The second bug does happen even if only levelz is installed. Just confirmed that on v1.0.6.
Here's the crash report for the soulsand/soil bug:

---- Minecraft Crash Report ----
// Don't do that.

Time: 9/10/21, 1:57 AM
Description: Ticking player

java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
	at net.minecraft.class_1324.method_6197(class_1324.java:73)
	at net.minecraft.class_1324.method_26835(class_1324.java:81)
	at net.minecraft.class_1309.method_29502(class_1309.java:498)
	at net.minecraft.class_1309.method_6126(class_1309.java:549)
	at net.minecraft.class_3222.method_6126(class_3222.java:960)
	at net.minecraft.class_1309.method_5670(class_1309.java:394)
	at net.minecraft.class_1297.method_5773(class_1297.java:444)
	at net.minecraft.class_1309.method_5773(class_1309.java:2308)
	at net.minecraft.class_1657.method_5773(class_1657.java:274)
	at net.minecraft.class_3222.method_14226(class_3222.java:466)
	at net.minecraft.class_3244.method_18784(class_3244.java:212)
	at net.minecraft.class_2535.method_10754(class_2535.java:238)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1324.method_6197(class_1324.java:73)
	at net.minecraft.class_1324.method_26835(class_1324.java:81)
	at net.minecraft.class_1309.method_29502(class_1309.java:498)
	at net.minecraft.class_1309.method_6126(class_1309.java:549)
	at net.minecraft.class_3222.method_6126(class_3222.java:960)
	at net.minecraft.class_1309.method_5670(class_1309.java:394)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$epj000$fillPatchouliContext(class_128.java:521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_128.method_560(class_128.java:267)
	at net.minecraft.class_3222.method_14226(class_3222.java:525)
	at net.minecraft.class_3244.method_18784(class_3244.java:212)
	at net.minecraft.class_2535.method_10754(class_2535.java:238)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Globox1997** [comment]
How can I reproduce this crash exactly?

**Comment by divinevtwo** [comment]
Max all skills and sprint jump on soulsand/soil while wearing soul speed III boots, should crash almost instantly under these circumstances

**Comment by Globox1997** [comment]
Tried to reproduce this bug as you mentioned but didn't get any crashes.

**Comment by divinevtwo** [comment]
That's akward but I guess it can't be helped then. Thanks for trying tho!

**Comment by Globox1997** [comment]
Maybe it got fixed with the latest update
