### ISSUE TITLE
[CRASH] java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Flamaghl** [Globox1997/LevelZ#223]
Hello,

I face this issue whenever I try to join a single player world, or sometimes I can load but right after moving a bit it the game crashes. It was fine before this morning, but I couldn't solve it
I haven't been able to figure out if the issue is from mod incompatibility or not, as the only lead I could find was "at net.levelz.mixin.misc.DrawableHelperAccessor.callFillGradient(DrawableHelperAccessor.java) ~[levelz-1.4.4.jar:?]" in the error + log reports :(

The whole error looks like this : 
[17:24:18] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'void net.minecraft.class_332.callFillGradient_$md$69a2ba$0(net.minecraft.class_1159, net.minecraft.class_287, int, int, int, int, int, int, int)'
	at net.levelz.mixin.misc.DrawableHelperAccessor.callFillGradient(DrawableHelperAccessor.java) ~[levelz-1.4.4.jar:?]
	at net.minecraft.class_329.renderTooltip(class_329.java:8569) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.handler$ehe000$renderCrosshairMixin(class_329.java:8539) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1736(class_329.java:458) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:213) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:862) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1177) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.11.jar:?]

Here are the logs + crash reports from curseforge :
[latest.log](https://github.com/Globox1997/LevelZ/files/10220090/latest.log)
[crash-2022-12-13_17.24.23-client.txt](https://github.com/Globox1997/LevelZ/files/10220093/crash-2022-12-13_17.24.23-client.txt)

Thanks !

**Comment by Globox1997** [comment]
Mh this might be a mod incompatibility.
Turn of the setting showLockedBlockInfo which is in the gui setting, this will fix the issue

**Comment by Flamaghl** [comment]
Will try that today and let you know, thanks ! :D

**Comment by Flamaghl** [comment]
Seems that it fixed it, many thanks
