### ISSUE TITLE
[Crash] Crashes on world start/ New world generation stuck at 0%

### ISSUE THREAD

**Issue by similarly** [Globox1997/LevelZ#265]
I can't tell if the issue is relevant to the mod, but I can't add it to my modpack

With mod turned on, the new world I try to create just gets stuck at 0%.
If I create new world without LevelZ, and then join with LevelZ on, it crashes with the following log:
But if I join with LevelZ and without RpgDifficulty, everything works.

```
---- Minecraft Crash Report ----
// My bad.

Time: 2023-04-23 19:48:37
Description: Ticking entity

java.lang.RuntimeException: Mixin transformation of net.rpgdifficulty.api.MobStrengthener failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.yungnickyoung.minecraft.travelerstitles.render.TitleRenderManager.handler$gld000$updateBiomeTitleMixin(TitleRenderManager.java:544)
	at com.yungnickyoung.minecraft.travelerstitles.render.TitleRenderManager.updateBiomeTitle(TitleRenderManager.java:211)
	at com.yungnickyoung.minecraft.travelerstitles.render.TitleRenderManager.playerTick(TitleRenderManager.java:94)
	at net.minecraft.class_746.handler$hdg001$onPostPlayerTick(class_746.java:9389)
	at net.minecraft.class_746.method_5773(class_746.java:245)
	at net.minecraft.class_638.method_18646(class_638.java:267)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_638.method_32124(class_638.java:250)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:246)
	at net.minecraft.class_310.method_1574(class_310.java:1851)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 22 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [rpgdifficulty.mixins.json:compat.ChangeAttributeMixin from mod rpgdifficulty] from phase [DEFAULT] in config [rpgdifficulty.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 25 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on rpgdifficulty.mixins.json:compat.ChangeAttributeMixin from mod rpgdifficulty->@Inject::changeAttributesMixin(Lnet/minecraft/class_1308;Lnet/minecraft/class_3218;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (Lnet/minecraft/class_1308;Lnet/minecraft/class_1937;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lnet/minecraft/class_1308;Lnet/minecraft/class_3218;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [INJECT Applicator Phase -> rpgdifficulty.mixins.json:compat.ChangeAttributeMixin from mod rpgdifficulty -> Apply Injections ->  -> Inject -> rpgdifficulty.mixins.json:compat.ChangeAttributeMixin from mod rpgdifficulty->@Inject::changeAttributesMixin(Lnet/minecraft/class_1308;Lnet/minecraft/class_3218;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:567)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1378)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 25 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.yungnickyoung.minecraft.travelerstitles.render.TitleRenderManager.handler$gld000$updateBiomeTitleMixin(TitleRenderManager.java:544)
	at com.yungnickyoung.minecraft.travelerstitles.render.TitleRenderManager.updateBiomeTitle(TitleRenderManager.java:211)
	at com.yungnickyoung.minecraft.travelerstitles.render.TitleRenderManager.playerTick(TitleRenderManager.java:94)
	at net.minecraft.class_746.handler$hdg001$onPostPlayerTick(class_746.java:9389)
	at net.minecraft.class_746.method_5773(class_746.java:245)
	at net.minecraft.class_638.method_18646(class_638.java:267)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_638.method_32124(class_638.java:250)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:246)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 246
	Entity Name: puggermugger
	Entity's Exact location: -51.33, 99.00, -34.68
	Entity's Block location: World: (-52,99,-35), Section: (at 12,3,13 in -4,6,-3; chunk contains blocks -64,-64,-48 to -49,319,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_638.method_32124(class_638.java:250)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:246)
	at net.minecraft.class_310.method_1574(class_310.java:1851)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
	

Full log:
[crash-2023-04-23_19.48.37-client.txt](https://github.com/Globox1997/LevelZ/files/11303784/crash-2023-04-23_19.48.37-client.txt)

**Comment by similarly** [comment]
Update: this only happens with RpgDifficulty I downloaded from modrinth, one from curseforge works with LevelZ perfectly fine, although they're same version

**Comment by Globox1997** [comment]
Do you use the latest version of rpgdifficulty and levelz?
