### ISSUE TITLE
Client-side code is accessed on server causing crash when WAILA is present

### ISSUE THREAD

**Issue by KaktuszSok** [Globox1997/LevelZ#325]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.25

### Mod Version

1.4.9-1.19.2

### Describe the Issue

Hello, launching a standalone server with this mod and wthit installed causes it to crash on startup. This is due to RenderInit class being accessed from the server.

Stacktrace:
```
[20:12:06] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'wthit'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.23.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.23.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.14.23-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.RuntimeException: Cannot load class net.levelz.init.RenderInit in environment type SERVER
	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.23.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.levelz.waila.LevelWailaBlockInfo.initialize(LevelWailaBlockInfo.java:20) ~[levelz-1.4.9.jar:?]
	at net.levelz.waila.LevelWailaPlugin.lambda$register$0(LevelWailaPlugin.java:16) ~[levelz-1.4.9.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.levelz.waila.LevelWailaPlugin.register(LevelWailaPlugin.java:16) ~[levelz-1.4.9.jar:?]
	at mcp.mobius.waila.plugin.PluginLoader.register(PluginLoader.java:120) ~[wthit-fabric-5.19.3.jar:?]
	at mcp.mobius.waila.plugin.PluginLoader.loadPlugins(PluginLoader.java:98) ~[wthit-fabric-5.19.3.jar:?]
	at mcp.mobius.waila.fabric.FabricWaila.onInitialize(FabricWaila.java:40) ~[wthit-fabric-5.19.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.23.jar:?]
	... 7 more
```

### latest.log

https://gist.github.com/KaktuszSok/f69c4f293c1bf4b05c734dbfd6934088

### Do you use any other mods except the required ones?

yes

**Comment by UAVwaffle** [comment]
Isn't waila a client-side mod? If I'm right it shouldn't be in your servers mod folder
