### ISSUE TITLE
Cannot get Levelz to load on my minecraft server

### ISSUE THREAD

**Issue by Ysus1** [Globox1997/LevelZ#351]
### Minecraft Version

1.20.x

### Mod Loader Version

fabric-api-0.92.2

### Mod Version

levelz-1.4.13

### Describe the Issue

When I attempt to load my server with the Levelz mod added to my mods folder in servers files, It will load up as normal but reaches a point at which it stops loading the server. It loads up to a point until it reaches ...6 More and everything stops loading and sits there and does nothing. The server never comes online.
I thought it might be an incompatiblity with the versions, so attempted to use all the different versions of Levelz to no avail.
Then thought it might be incompatible with other mods, but even with just levelz installed and its dependincies It still stopped at the same point.

### latest.log

[latest.log](https://github.com/user-attachments/files/16246658/latest.log)
[09:39:28] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.11
[09:39:28] [ForkJoinPool-1-worker-2/WARN]: Mod mr_dungeons_andtaverns uses the version 3.0.3.f which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'f'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[09:39:28] [main/INFO]: Loading 98 mods:
	- amplified_nether 1.2.5
	- bclib 3.0.14
	   \-- wunderlib 1.1.5
	- betterend 4.0.11
	- bettermineshafts 1.20-Fabric-4.0.4
	   \-- org_reflections_reflections 0.10.2
	- betternether 9.0.10
	- betterstrongholds 1.20-Fabric-4.0.3
	- chunky 1.3.146
	- cloth-config 11.1.106
	   \-- cloth-basic-math 0.6.1
	- connectiblechains 2.2.1+1.20.1
	- easyanvils 8.0.2
	- easymagic 8.0.1
	- fabric-api 0.92.2+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.2+85287f9f77
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- forgeconfigapiport 8.0.0
	- frycmobvariants 4.4.1+1.20
	- herdspanic 1.1.0
	- java 17
	- levelz 1.4.13
	- libz 1.0.1
	- minecraft 1.20.1
	- mr_dungeons_andtaverns 3.0.3.f
	- puzzleslib 8.1.21
	   \-- puzzlesaccessapi 8.0.7
	- seasons 2.3+1.20
	- tabtps-fabric 1.3.18
	   |-- adventure-platform-fabric 5.10.0-SNAPSHOT
	   |    |-- net_kyori_adventure-api 4.14.0
	   |    |-- net_kyori_adventure-key 4.14.0
	   |    |-- net_kyori_adventure-platform-api 4.3.0
	   |    |-- net_kyori_adventure-text-logger-slf4j 4.14.0
	   |    |-- net_kyori_adventure-text-minimessage 4.14.0
	   |    |-- net_kyori_adventure-text-serializer-ansi 4.14.0
	   |    |-- net_kyori_adventure-text-serializer-gson 4.14.0
	   |    |-- net_kyori_adventure-text-serializer-json 4.14.0
	   |    |-- net_kyori_adventure-text-serializer-plain 4.14.0
	   |    |-- net_kyori_ansi 1.0.1
	   |    |-- net_kyori_examination-api 1.3.0
	   |    \-- net_kyori_examination-string 1.3.0
	   |-- cloud 1.8.3
	   |    |-- cloud_commandframework_cloud-brigadier_ 1.8.3
	   |    |-- cloud_commandframework_cloud-core_ 1.8.3
	   |    |-- cloud_commandframework_cloud-services_ 1.8.3
	   |    |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |    \-- io_leangen_geantyref_geantyref 1.3.13
	   |-- cloud_commandframework_cloud-minecraft-extras 1.8.3
	   |-- com_typesafe_config 1.4.2
	   |-- net_kyori_adventure-serializer-configurate4 4.14.0
	   |-- net_kyori_adventure-text-feature-pagination 4.0.0-SNAPSHOT
	   |-- net_kyori_adventure-text-serializer-legacy 4.14.0
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- vanillatweaks 1.5.71
	- yungsapi 1.20-Fabric-4.0.5
	   |-- mixinextras 0.3.5
	   \-- org_javassist_javassist 3.29.2-GA
	- yungsextras 1.20-Fabric-4.0.3
[09:39:29] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/minecraft/multicraft/servers/server783679/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[09:39:29] [main/INFO]: Compatibility level set to JAVA_17
[09:39:29] [main/WARN]: Reference map 'yungsextras.refmap.json' for yungsextras.mixins.json could not be read. If this is a development environment you can ignore this message
[09:39:29] [main/WARN]: Reference map 'yungsextras.refmap.json' for yungsextras_fabric.mixins.json could not be read. If this is a development environment you can ignore this message
[09:39:30] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[09:39:40] [main/INFO]: [bclib] Added Config betternether.main to auto sync (file hash)
[09:39:40] [main/INFO]: [bclib] Added Config betternether.generator to auto sync (file hash)
[09:39:40] [main/INFO]: [bclib] Added Config betternether.blocks to auto sync (file hash)
[09:39:40] [main/INFO]: [bclib] Added Config betternether.items to auto sync (file hash)
[09:39:40] [main/INFO]: [bclib] Added Config betternether.biomes to auto sync (file hash)
[09:39:40] [main/INFO]: [bclib] Added Config betternether.mobs to auto sync (file hash)
[09:39:40] [main/INFO]: [bclib] Added Config betternether.recipes to auto sync (file hash)
[09:39:41] [main/WARN]: [bclib] Recipe betternether:bone_block_bone_button only takes in a single item and should be shapeless
[09:39:41] [main/INFO]: [bclib] Added Config bclib.generator to auto sync (file hash)
[09:39:41] [main/INFO]: [bclib] Added Config bclib.main to auto sync (content diff)
[09:39:41] [main/INFO]: [bclib] Added Config bclib.biomes to auto sync (file hash)
[09:39:41] [main/INFO]: [bclib] Added Config betterend.entities to auto sync (file hash)
[09:39:41] [main/INFO]: [bclib] Added Config betterend.blocks to auto sync (file hash)
[09:39:41] [main/INFO]: [bclib] Added Config betterend.items to auto sync (file hash)
[09:39:41] [main/INFO]: [bclib] Added Config betterend.biomes to auto sync (file hash)
[09:39:41] [main/INFO]: [bclib] Added Config betterend.recipes to auto sync (file hash)
[09:39:41] [main/INFO]: [bclib] Added Config betterend.enchantments to auto sync (file hash)
[09:39:50] [main/INFO]: Reflections took 42 ms to scan 1 urls, producing 1 keys and 2 values
[09:39:50] [main/INFO]: Reflections took 2 ms to scan 1 urls, producing 1 keys and 2 values
[09:39:50] [main/INFO]: [betternether] =^..^=    BetterNether for 1.20    =^..^=
[09:39:51] [main/INFO]: Reflections took 4 ms to scan 1 urls, producing 1 keys and 2 values
[09:39:51] [main/INFO]: Reflections took 10 ms to scan 1 urls, producing 1 keys and 2 values
[09:39:51] [main/INFO]: Initialized entity types.
[09:39:51] [main/INFO]: Constructing common components for easyanvils:main
[09:39:51] [main/INFO]: Constructing common components for easymagic:main
[09:39:51] [main/INFO]: Constructing common components for puzzleslib:main
[09:39:51] [main/INFO]: [Fabric Seasons] Trying to read config file...
[09:39:51] [main/INFO]: [Fabric Seasons] A config file was found, loading it..
[09:39:51] [main/INFO]: [Fabric Seasons] Successfully loaded config file.
[09:39:51] [main/INFO]: Done initializing TabTPS.
[09:39:51] [main/INFO]: Setup Complete
[09:39:51] [main/INFO]: Reflections took 5 ms to scan 1 urls, producing 1 keys and 4 values
[09:39:51] [main/INFO]: Reflections took 2 ms to scan 1 urls, producing 1 keys and 4 values
[09:39:51] [main/INFO]: Reflections took 1 ms to scan 1 urls, producing 1 keys and 2 values
[09:39:52] [main/INFO]: Reflections took 2 ms to scan 1 urls, producing 1 keys and 2 values
[09:39:52] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'levelz'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.11.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/libz/api/ConfigSync
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.levelz.init.ConfigInit.<clinit>(ConfigInit.java:12) ~[levelz-1.4.13.jar:?]
	at net.levelz.LevelzMain.onInitialize(LevelzMain.java:13) ~[levelz-1.4.13.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.libz.api.ConfigSync
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.levelz.init.ConfigInit.<clinit>(ConfigInit.java:12) ~[levelz-1.4.13.jar:?]
	at net.levelz.LevelzMain.onInitialize(LevelzMain.java:13) ~[levelz-1.4.13.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 6 more

**Comment by Globox1997** [comment]
Update LibZ

**Comment by qwertyuioplkggdfdf** [comment]
hey does this mod work in 1.21 at all i tried it and it just crashes my game i have all the mods it need to work aswell
