### ISSUE TITLE
Crash with magic leveling

### ISSUE THREAD

**Issue by Yarimargarin** [Globox1997/LevelZ#370]
### Minecraft Version

1.21.x

### Mod Loader Version

0.16.9

### Mod Version

2.0.2+1.21.1

### Describe the Issue

After leveling "Magic", ı dropped to lava and game crashed ,since my character still inside the lava, everytime ı login to that world, game crashes

This seems to be the problem;

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_5643(net.minecraft.class_1282, float)" because the return value of "net.minecraft.class_1282.method_5529()" is null
	at knot//net.levelz.util.BonusHelper.damageReflectionBonus(BonusHelper.java:382)
	at knot//net.minecraft.class_1657.handler$dbg000$levelz$damageMixin(class_1657.java:17505)
	at knot//net.minecraft.class_1657.method_5643(class_1657.java:958)
	at knot//net.minecraft.class_3222.method_5643(class_3222.java:811)
	at knot//net.minecraft.class_1297.method_5730(class_1297.java:605)
	at knot//net.minecraft.class_1297.method_5670(class_1297.java:545)
	at knot//net.minecraft.class_1309.method_5670(class_1309.java:406)
	at knot//net.minecraft.class_1297.method_5773(class_1297.java:487)
	at knot//net.minecraft.class_1309.method_5773(class_1309.java:2468)
	at knot//net.minecraft.class_1657.method_5773(class_1657.java:312)
	at knot//net.minecraft.class_3222.method_14226(class_3222.java:588)
	at knot//net.minecraft.class_3244.method_18784(class_3244.java:268)
	at knot//net.minecraft.class_2535.method_10754(class_2535.java:401)
	at knot//net.minecraft.class_3242.method_14357(class_3242.java:176)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1032)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:114)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### latest.log

[crash-2024-11-30_17.45.28-server.txt](https://github.com/user-attachments/files/17965776/crash-2024-11-30_17.45.28-server.txt)

### Do you use any other mods except the required ones?

Yes

**Comment by Globox1997** [comment]
Will be fixed soon.

**Comment by Globox1997** [comment]
[levelz-2.0.3.zip](https://github.com/user-attachments/files/17966292/levelz-2.0.3.zip)
Use this as a hotifx

**Comment by nateify** [comment]
I am still getting a crash with the magic skill on LevelZ 2.0.3 on Fabric for 1.21.1 with other mods installed:

https://mclo.gs/KbNF5QP

**Comment by nateify** [comment]
I noticed it is not crashing in single player but does crash in multiplayer. I am using a custom modpack which was exported to MRPACK format and being used on both the client and server side. Not sure the best way to test for incompatibilities aside from enabling mods one at a time on both ends simultaneously?

These mods marked as client only I manually installed on the server since they do provide extra functionality when on both ends:
        areas
        xaeros-minimap
        xaeros-world-map
        rei

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/LevelZ/commit/0057acf4e16914a4844b9cb4b0ab42e11e034664](https://github.com/Globox1997/LevelZ/commit/0057acf4e16914a4844b9cb4b0ab42e11e034664)
