### ISSUE TITLE
LevelZ damageReflectionBonus Crash With log(1.21.1)

### ISSUE THREAD

**Issue by Darkelfy** [Globox1997/LevelZ#373]
### Minecraft Version

1.21.x

### Mod Loader Version

Fabric 1.21.1

### Mod Version

LevelZ 2.0.2

### Describe the Issue

I went into the lava pool and it crashed
I am not a good gamer nor coder, So I just put crash log into chatgpt, It said damageReflctionBonus Error, or conflict with Aether or FabricShieldLib.

↓It is a chatgpt chat log
The crash log indicates an issue caused by the LevelZ mod. Specifically, the error occurred in the damageReflectionBonus method in the BonusHelper class (line 382). The root cause is a NullPointerException when attempting to call method_5643 on a null return value from method_5529.

### latest.log

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024-12-14 03:02:52
Description: Ticking player

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_5643(net.minecraft.class_1282, float)" because the return value of "net.minecraft.class_1282.method_5529()" is null
	at knot//net.levelz.util.BonusHelper.damageReflectionBonus(BonusHelper.java:382)
	at knot//net.minecraft.class_1657.handler$bmd000$levelz$damageMixin(class_1657.java:7505)
	at knot//net.minecraft.class_1657.method_5643(class_1657.java:958)
	at knot//net.minecraft.class_3222.method_5643(class_3222.java:811)
	at knot//net.minecraft.class_1297.method_5730(class_1297.java:605)
	at knot//net.minecraft.class_1297.method_5670(class_1297.java:545)
	at knot//net.minecraft.class_1309.method_5670(class_1309.java:406)
	at knot//net.minecraft.class_1297.method_5773(class_1297.java:487)
	at knot//net.minecraft.class_1309.method_5773(class_1309.java:2468)
	at knot//net.minecraft.class_1657.method_5773$mixinextras$wrapped$248(class_1657.java:312)
	at knot//net.minecraft.class_1657.mixinextras$bridge$method_5773$mixinextras$wrapped$248$249(class_1657.java)
	at knot//net.minecraft.class_1657.wrapMethod$zda000$aether$aetherFabric$playerTickEvents(class_1657.java:3480)
	at knot//net.minecraft.class_1657.method_5773(class_1657.java)
	at knot//net.minecraft.class_3222.method_14226(class_3222.java:588)
	at knot//net.minecraft.class_3244.method_18784(class_3244.java:268)
	at knot//net.minecraft.class_2535.method_10754(class_2535.java:401)
	at knot//net.minecraft.class_3242.method_14357(class_3242.java:176)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1032)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:114)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at knot//net.levelz.util.BonusHelper.damageReflectionBonus(BonusHelper.java:382)
	at knot//net.minecraft.class_1657.handler$bmd000$levelz$damageMixin(class_1657.java:7505)
	at knot//net.minecraft.class_1657.method_5643(class_1657.java:958)
	at knot//net.minecraft.class_3222.method_5643(class_3222.java:811)
	at knot//net.minecraft.class_1297.method_5730(class_1297.java:605)
	at knot//net.minecraft.class_1297.method_5670(class_1297.java:545)
	at knot//net.minecraft.class_1309.method_5670(class_1309.java:406)
	at knot//net.minecraft.class_1297.method_5773(class_1297.java:487)
	at knot//net.minecraft.class_1309.method_5773(class_1309.java:2468)
	at knot//net.minecraft.class_1657.method_5773$mixinextras$wrapped$248(class_1657.java:312)
	at knot//net.minecraft.class_1657.mixinextras$bridge$method_5773$mixinextras$wrapped$248$249(class_1657.java)
	at knot//net.minecraft.class_1657.wrapMethod$zda000$aether$aetherFabric$playerTickEvents(class_1657.java:3480)
	at knot//net.minecraft.class_1657.method_5773(class_1657.java)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 4
	Entity Name: Viidhh
	Entity's Exact location: 882.47, -17.75, -1261.70
	Entity's Block location: World: (882,-18,-1262), Section: (at 2,14,2 in 55,-2,-79; chunk contains blocks 880,-64,-1264 to 895,319,-1249), Region: (1,-3; contains chunks 32,-96 to 63,-65, blocks 512,-64,-1536 to 1023,319,-1025)
	Entity's Momentum: 0.00, -0.04, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at knot//net.minecraft.class_3222.method_14226(class_3222.java:588)
	at knot//net.minecraft.class_3244.method_18784(class_3244.java:268)
	at knot//net.minecraft.class_2535.method_10754(class_2535.java:401)
	at knot//net.minecraft.class_3242.method_14357(class_3242.java:176)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1032)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:114)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 995250232 bytes (949 MiB) / 2105540608 bytes (2008 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 7600X 6-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 97 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 4.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Microsoft Basic Display Adapter
	Graphics card #0 vendor: Microsoft
	Graphics card #0 VRAM (MiB): 0.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 10.0.22621.1
	Graphics card #1 name: AMD Radeon(TM) Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc.
	Graphics card #1 VRAM (MiB): 512.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.12019.1028
	Graphics card #2 name: NVIDIA GeForce RTX 4070
	Graphics card #2 vendor: NVIDIA
	Graphics card #2 VRAM (MiB): 12282.00
	Graphics card #2 deviceId: VideoController3
	Graphics card #2 versionInfo: 32.0.15.6614
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 5.60
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 5.60
	Memory slot #1 type: Unknown
	Virtual memory max (MiB): 38337.07
	Virtual memory used (MiB): 22666.59
	Swap memory total (MiB): 6400.00
	Swap memory used (MiB): 94.09
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 1175577.75, total: 1906843.00
	Space in storage for workdir (MiB): available: 1175577.75, total: 1906843.00
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx8192m
	Fabric Mods: 
		aether: The Aether 1.5.1-beta.4
			accessories: Accessories 1.1.0-beta.16+1.21.1
			cumulus_menus: Cumulus 1.1.1
			forgeconfigapiport: Forge Config API Port 21.1.1
				com_electronwill_night-config_core: core 3.8.0
				com_electronwill_night-config_toml: toml 3.8.0
			mixinextras: MixinExtras 0.5.0-beta.3
			mm_shedaniel: Manningham Mills (shedaniel's fork) 2.4.1
			nitrogen_internals: Nitrogen 1.1.21
		autofish: XPlus Autofish 1.3.4-fabric-mc1.21.1
		bowinfinityfix: Bow Infinity Fix 3.1.0
		cardinal-components: Cardinal Components API 6.1.1
			cardinal-components-base: Cardinal Components API (base) 6.1.1
			cardinal-components-block: Cardinal Components API (blocks) 6.1.1
			cardinal-components-chunk: Cardinal Components API (chunks) 6.1.1
			cardinal-components-entity: Cardinal Components API (entities) 6.1.1
			cardinal-components-item: Cardinal Components API (items) 6.1.1
			cardinal-components-level: Cardinal Components API (world saves) 6.1.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 6.1.1
			cardinal-components-world: Cardinal Components API (worlds) 6.1.1
		clearvision_by_kapiteon: ClearVision by kapiteon 1.0.0
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 19.0.0.1
		cristellib: Cristel Lib 1.2.8
			blue_endless_jankson: jankson 1.2.3
		entityculling: EntityCulling 1.7.2
		fabric-api: Fabric API 0.109.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.70+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.18+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.2+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.2+e60e56d419
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.0+da19b51a19
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.23+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.0+01d9a51c19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.3+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.87+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.2+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabricloader: Fabric Loader 0.16.9
		fabricshieldlib: Fabric Shield Lib 1.7.2-1.21.1
			midnightlib: MidnightLib 1.5.8
			mm: Manningham Mills 2.3
		fallingtree: FallingTree 1.21.1.2
		healthindicatortxf: Health Indicator TXF 1.21.1-1.3.2-fabric
			configlibtxf: ConfigLib TXF 7.2.5-fabric
		infinityandmending: Infinity and Mending 1.21.x-1.0.0
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 19.21.0.247
		justzoom: Just Zoom 2.0.0
		konkrete: Konkrete 1.9.9
		krypton: Krypton 0.2.8
			com_velocitypowered_velocity-native: velocity-native 3.3.0-SNAPSHOT
		levelz: LevelZ 2.0.2
		libz: LibZ 1.0.3
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.15.2
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.15.2
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.15.2
		minecraft: Minecraft 1.21.1
		mobz: MobZ 4.3.2
		modernfix: ModernFix 5.19.5+mc1.21.1
		modmenu: Mod Menu 11.0.3
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		monolib: MonoLib 1.4.1
		mousetweaks: Mouse Tweaks 2.26
		owo: oωo 0.12.15+1.21
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_jankson: jankson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		sodium: Sodium 0.6.0+mc1.21.1
		stackable: Stackable 1.3
		t_and_t: Towns and Towers 1.13.2
		toolsofobsidian: Tools Of Obsidian 1.21.1-1.7.0
		trajectory_estimation: Trajectory Estimation 1.0.3.1
		travelersbackpack: Traveler's Backpack 10.1.3
		villagerinabucket: Villager In A Bucket 1.21.1-1.0.1
		xaerominimap: Xaero's Minimap 24.6.1
	Server Running: true
	Player Count: 1 / 8; [class_3222['Viidhh'/4, l='ServerLevel[새로운 세계]', x=882.47, y=-17.75, z=-1261.70]]
	Active Data Packs: vanilla, fabric, accessories, aether, fabric-convention-tags-v2, fabricshieldlib, levelz, mobz, t_and_t, toolsofobsidian, travelersbackpack, villagerinabucket, builtin/aether_accessories
	Available Data Packs: accessories, aether, builtin/aether_accessories, builtin/aether_ruined_portal, builtin/aether_temporary_freezing, bundle, fabric, fabric-convention-tags-v2, fabricshieldlib, levelz, mobz, t_and_t, toolsofobsidian, trade_rebalance, travelersbackpack, vanilla, villagerinabucket
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	World Seed: 5396333420792893766
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.21.1

**Comment by nateify** [comment]
Just wanted to add my log to this issue as I am also seeing the same thing, it happened after a thrown ender pearl
https://mclo.gs/XcFx6Jn

**Comment by EnierAragon** [comment]
In my personal mod pack, the same glitch occurred when I was burning to test my armor with fire protection 5.
[https://mclo.gs/vo3Asgp](https://mclo.gs/vo3Asgp)

**Comment by nateify** [comment]
I'm able to somewhat reliably trigger this crash when in the Nether from lava damage or this type of damage from a Naga modded mob from BetterNether:

https://mclo.gs/I9jWHxJ

**Comment by nateify** [comment]
I have figured out a way to reliably trigger the issue with the minimum amount of mods required for only LevelZ plus StackDeobfuscator, mixintrace, and noisium.

Steps to reproduce:

1. Create a new world
2. Travel to the Nether
3. Level up the Luck stat to 6/20
4. Light self on fire
5. Produces this crash report: https://mclo.gs/ulrK9Zt

Able to reproduce consistently by traveling to the Nether and taking fire damage

**Comment by Globox1997** [comment]
Fixed with v2.0.3
