### ISSUE TITLE
Crash When Opening Inventory involving Tooltips and invalid skill. 

### ISSUE THREAD

**Issue by FranM06** [Globox1997/LevelZ#375]
### Minecraft Version

1.21.x

### Mod Loader Version

Fabric API 0.92.2+1.20.1

### Mod Version

1.4.13+1.20.1

### Describe the Issue

While being on a server, once i open the inventory it crashes, i looked at the crash report and it seems that is specifically related to how LevelZ handles player stats and tooltips when opening the inventory. Does someone know how to fix this, or if theres a similar issue that has already been fixed plz tell me. Thanks
all mods installed: 

AdditionZ 1.3.2
Runtime Resource Pack 0.8.1
AdvancementsFullscreen 1.0
AdvancementsSearch 1.0
AdventureZ 1.4.20
Aged-Addition 1.0.6
Almanac 1.0.2
Amarite 1.0.8
Cardinal Components API (base) 5.2.2
Cardinal Components API (blocks) 5.2.2
Cardinal Components API (entities) 5.2.2
Reach Entity Attributes 2.4.0
Ambient Environment 11.0.0.1
Another Furniture 1.20.1-3.0.1
Antique Atlas 2.10.0+1.20
AppleSkin 2.5.1+mc1.20
Aquamirae 6
Architectury 9.2.14
Astrocraft 1.4.5+1.20.1
Async Locator 1.3.0
Athena 3.1.2
AutoTag Convention 2.0.2+1.20
AutoTag 2.0.2+1.20
AzureLib 2.0.39
BackSlot 1.2.15
Amecs API 1.5.0+mc1.20-pre1
BackSlot Addon 1.1.1
BadOptimizations 2.2.0
[Let's Do] Bakery 2.0.3
Balm 7.3.9
KumaAPI 20.1.8
Building But Better 1.20.1-fabric-1.0.2
BCLib 3.0.14
WunderLib 1.1.5
Create: Bells & Whistles 0.4.5
Better Archeology 1.2.1-1.20.1
Better Combat 1.8.6+1.20.1
YUNG's Better Desert Temples 1.20-Fabric-3.0.3
reflections 0.10.2
Better End 4.0.11
YUNG's Better End Island 1.20-Fabric-2.0.6
YUNG's Better Nether Fortresses 1.20-Fabric-2.0.6
YUNG's Better Jungle Temples 1.20-Fabric-2.0.5
YUNG's Better Ocean Monuments 1.20-Fabric-3.0.4
Birds Boids 1.1.0
Blur (Fabric) 3.1.0
MidnightLib 1.4.1
Satin 1.13.0
Boids 1.2.2
jankson 1.2.3
Borderless Mining 1.1.8+1.20.1
[Let's Do] Brewery 2.0.3
Camera Overhaul 1.4.1-fabric-universal
[Let's Do] Candlelight 2.0.2
Chalk 2.2.4
releasetypeutils 2.1.0
Simple Fabric Libs 2.0.0
Chalk: Colorful-Addon 2.1.1+1.19.3
Chipped 3.0.7
Cloth Config v11 11.1.136
cloth-basic-math 0.6.1
Combat Roll 1.3.3+1.20.1
Connectible Chains 2.2.1+1.20.1
Create: Copycats+ 2.1.4+mc.1.20.1-fabric
Couplings 1.9.5+1.20
Crawl 0.12.0
Manningham Mills 2.3
Create 0.5.1-j-build.1609+mc1.20.1
jsr305 3.0.2
Flywheel 0.6.11-4
Milk Lib 1.2.60
Dripstone Fluid Lib 3.0.2
Porting Lib Accessors 2.3.8+1.20.1
Porting Lib Core 2.3.8+1.20.1
Porting Lib Base 2.3.8+1.20.1
Porting Lib Config 2.3.8+1.20.1
Porting Lib Gui Utils 2.3.8+1.20.1
Porting Lib Lazy Register 2.3.8+1.20.1
Porting Lib Mixin Extensions 2.3.8+1.20.1
Porting Lib Utility 2.3.8+1.20.1
Porting Lib Brewing 2.3.8+1.20.1
Porting Lib Client Events 2.3.8+1.20.1
Porting Lib Entity 2.3.8+1.20.1
Porting Lib Extensions 2.3.8+1.20.1
Porting Lib Attributes 2.3.8+1.20.1
Porting Lib Common 2.3.8+1.20.1
Porting Lib Models 2.3.8+1.20.1
Porting Lib Networking 2.3.8+1.20.1
Porting Lib Obj Loader 2.3.8+1.20.1
Porting Lib Model Loader 2.3.8+1.20.1
Porting Lib Tags 3.0
Porting Lib Tool Actions 2.3.8+1.20.1
Porting Lib Transfer 2.3.8+1.20.1
Porting Lib Fluids 2.3.8+1.20.1
Registrate for Fabric 1.3.79-MC1.20.1
Porting Lib Data 2.1.1090+1.20
Porting Lib GameTest 2.1.1090+1.20
Porting Lib Model Generators 2.1.1090+1.20
Porting Lib Model Materials 2.1.1090+1.20
Create Deco 2.0.2-1.20.1-fabric 

### latest.log
Description: Screen rendering
at knot//net.levelz.stats.Skill.valueOf(Skill.java:9)
at knot//net.levelz.stats.PlayerStatsManager.getLevel(PlayerStatsManager.java:129)
at knot//net.levelz.stats.PlayerStatsManager.playerLevelisHighEnough(PlayerStatsManager.java:198)
at knot//net.minecraft.class_1799.getAdditionalTooltip(class_1799.java:9743)
at knot//net.minecraft.class_1799.handler$gaj001$levelz$getTooltipMixin(class_1799.java:9640)
at knot//net.minecraft.class_1799.method_7950(class_1799.java:647)
at knot//net.minecraft.class_437.method_25408(class_437.java:225)
at knot//net.minecraft.class_465.method_51454(class_465.java:183)
at knot//net.minecraft.class_465.method_2380(class_465.java:178)
at knot//net.minecraft.class_490.method_25394(class_490.java:92)
at knot//net.minecraft.class_437.method_47413(class_437.java:110)
at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$302(class_757.java)
at knot//net.minecraft.class_757.wrapOperation$efj000$fancymenu$wrapRenderScreenFancyMenu(class_757.java:8107)
at knot//net.minecraft.class_757.mixinextras$bridge$wrapOperation$efj000$fancymenu$wrapRenderScreenFancyMenu$303(class_757.java)
at knot//net.minecraft.class_757.wrapOperation$fjm000$konkrete$wrapRenderScreenKonkrete(class_757.java:11628)
at knot//net.minecraft.class_757.method_3192(class_757.java:945)
at knot//net.minecraft.class_310.method_1523(class_310.java:1219)
at knot//net.minecraft.class_310.method_1514(class_310.java:802)
at knot//net.minecraft.client.main.Main.main(Main.java:250)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
Stacktrace:
at knot//net.minecraft.class_638.method_8538(class_638.java:458)
at knot//net.minecraft.class_310.method_1587(class_310.java:2406)
at knot//net.minecraft.class_310.method_1514(class_310.java:821)
at knot//net.minecraft.client.main.Main.main(Main.java:250)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
-- Last reload --
Details:
Reload number: 1
Reload reason: initial
Finished: Yes
Packs: vanilla, fabric, extendeddrawersaddon:addon, seasons:seasonal_lush_caves, Moonlight Mods Dynamic Assets, vinery:bushy_leaves, meadow:better_leaves, file/§fFancy§5Fast §2Bushy Leaves§0.zip, file/FreshAnimations_v1.9.2.zip, file/Expressive Fresh Moves v3.0.1.zip, file/FA+Spiders-v1.1.zip, file/FA+Quivers-v1.1.zip, file/FA+Objects-v1.1.zip, file/FA+Details-v1.1.zip, file/FA+Classic_Horses-v1.2.zip, file/FA+Emissive-v1.2.zip, file/Let's Do - Pixel Perfect.zip, natures_spirit:plank_consistency, natures_spirit:emissive_ores_compatibility, aged_dirt_replace_to_gray, aged_guide_book, aged_welcome_screen, fixes_for_aged, loadmyresources.hiddenpack, Essential Assets, essential

**Comment by Globox1997** [comment]
This is an older version issue, out of time reasons I only work on the latest version of my mods.

**Comment by muratkertil402-lgtm** [comment]
> This is an older version issue, out of time reasons I only work on the latest version of my mods.

can you please all the good mods only have 1.20.1 and i cant play with my friends
by the way they dont have the sameproblem for some reason
