### ISSUE TITLE
Incompatibility with MCDA

### ISSUE THREAD

**Issue by chronosacaria** [Globox1997/LevelZ#38]
Hello, my friend!

I hope you are well. Looks like there is an issue between MCDA (MC Dungeons Armors) and LevelZ. It only seems to occur when LevelZ is installed, though. Here is the crash that I am getting:

```
java.lang.AbstractMethodError: Receiver class chronosacaria.mcda.items.ArmorSets does not define or inherit an implementation of the resolved method 'abstract java.lang.String getName()' of interface net.minecraft.item.ArmorMaterial.
	at net.minecraft.screen.ScreenHandler.handler$zfk000$internalOnSlotClickMixin(ScreenHandler.java:906) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.61-v2.jar:?]
	at net.minecraft.screen.ScreenHandler.internalOnSlotClick(ScreenHandler.java:405) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.61-v2.jar:?]
	at net.minecraft.screen.ScreenHandler.onSlotClick(ScreenHandler.java:284) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.61-v2.jar:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.onClickSlot(ServerPlayNetworkHandler.java:1390) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.61-v2.jar:?]
	at net.minecraft.network.packet.c2s.play.ClickSlotC2SPacket.apply(ClickSlotC2SPacket.java:55) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.61-v2.jar:?]
	at net.minecraft.network.packet.c2s.play.ClickSlotC2SPacket.apply(ClickSlotC2SPacket.java:11) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.61-v2.jar:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:21) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.61-v2.jar:?]
	at net.minecraft.server.ServerTask.run(ServerTask.java:18) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.61-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:151) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.61-v2.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.61-v2.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:788) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.61-v2.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:164) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.61-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:125) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.61-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:770) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.61-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:764) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.61-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:134) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.61-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:749) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.61-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:701) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.61-v2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.61-v2.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

I also got reports of this crash happening as well: 
```[Server thread/ERROR]: Encountered an unexpected exception
java.lang.AbstractMethodError: Receiver class chronosacaria.mcda.items.ArmorSets does not define or inherit an implementation of the resolved method 'abstract java.lang.String method_7694()' of interface net.minecraft.class_1741.
	at net.minecraft.class_1738.handler$bkf000$useMixin(class_1738.java:543) ~[intermediary-server.jar:?]
	at net.minecraft.class_1738.method_7836(class_1738.java:122) ~[intermediary-server.jar:?]
	at net.minecraft.class_1799.method_7913(class_1799.java:254) ~[intermediary-server.jar:?]
	at net.minecraft.class_3225.method_14256(class_3225.java:282) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_12065(class_3244.java:1086) ~[intermediary-server.jar:?]
	at net.minecraft.class_2886.method_12550(class_2886.java:25) ~[intermediary-server.jar:?]
	at net.minecraft.class_2886.method_11054(class_2886.java:7) ~[intermediary-server.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

I noticed that you had mixins named `internalOnSlotClickMixin` and `useMixin`, so I thought it would be something on LevelZ end, but, please let me know if there is anything that I can do on my end to help with this issue. 

Be blessed!
Chronosacaria

**Comment by chronosacaria** [comment]
Okay, I was able to resolve this issue. Thanks, Globox_Z!

**Comment by Globox1997** [comment]
Thank you and be blessed too :)
