### ISSUE TITLE
Crash on 1.18

### ISSUE THREAD

**Issue by mikeydoom** [Globox1997/LevelZ#59]
`---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 12/1/21, 10:44 PM
Description: Starting integrated server

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3324 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:234)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_310.method_29603(class_310.java:2048)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:277)
	at net.minecraft.class_310.method_29610(class_310.java:2048)
	at net.minecraft.class_310.method_29608(class_310.java:2021)
	at net.minecraft.class_310.method_29605(class_310.java:2122)
	at net.minecraft.class_410.method_37054(class_410.java:56)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:121)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:218)
	at net.minecraft.class_310.method_1523(class_310.java:1145)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229)
	... 33 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [levelz.mixins.json:player.PlayerManagerMixin] from phase [DEFAULT] in config [levelz.mixins.json] from mod [levelz] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 36 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded NullPointerException whilst transforming the mixin class: [INJECT Applicator Phase -> levelz.mixins.json:player.PlayerManagerMixin -> Apply Injections -> PreInject -> levelz.mixins.json:player.PlayerManagerMixin->@Inject::respawnPlayerMixin(Lnet/minecraft/class_3222;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_2338;FZLnet/minecraft/class_3218;Ljava/util/Optional;Lnet/minecraft/class_3218;Lnet/minecraft/class_3222;)V from mod levelz]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1390)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 36 more
Caused by: java.lang.NullPointerException: Cannot read field "desc" because "frame[varInsn.var]" is null
	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:546)
	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:336)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.preInject(CallbackInjector.java:477)
	at org.spongepowered.asm.mixin.injection.code.Injector.preInject(Injector.java:258)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.preInject(InjectionInfo.java:436)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1367)
	... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:234)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_310.method_29603(class_310.java:2048)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:277)
	at net.minecraft.class_310.method_29610(class_310.java:2048)
	at net.minecraft.class_310.method_29608(class_310.java:2021)
	at net.minecraft.class_310.method_29605(class_310.java:2122)
	at net.minecraft.class_410.method_37054(class_410.java:56)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:121)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)

-- Starting integrated server --
Details:
	Level ID: New World
	Level Name: New World
Stacktrace:
	at net.minecraft.class_310.method_29610(class_310.java:2048)
	at net.minecraft.class_310.method_29608(class_310.java:2021)
	at net.minecraft.class_310.method_29605(class_310.java:2122)
	at net.minecraft.class_410.method_37054(class_410.java:56)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:121)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:218)
	at net.minecraft.class_310.method_1523(class_310.java:1145)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_410
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:218)
	at net.minecraft.class_310.method_1523(class_310.java:1145)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: Default, Fabric Mods, MedievalMusic.zip, MedievalMusic2.zip, lambdabettergrass/default
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2409)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18
	Minecraft Version ID: 1.18
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2458167496 bytes (2344 MiB) / 3854565376 bytes (3676 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2488
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9709
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37548.35
	Virtual memory used (MB): 19500.97
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 49.09
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6144m -Xms256m
	Fabric Mods: 
		apoli: Apoli 2.1.0
		appleskin: AppleSkin mc1.18-2.2.0
		architectury: Architectury 3.1.44
		axesareweapons: Axes Are Weapons 1.5.1
		betterf3: BetterF3 1.1.5
		blue_endless_jankson: jankson 1.2.1
		bountiful: Bountiful 2.0.1
		calio: Calio 1.4.2
		cardinal-components-base: Cardinal Components API (base) 4.0.0-alpha.1+21w37a
		cardinal-components-entity: Cardinal Components API (entities) 4.0.0-alpha.1+21w37a
		citresewn: CITResewn 0.8.1-1.18
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config: Cloth Config v6 6.0.43
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps 8.0.1
		collective-fabric: Collective (Fabric) 3.9
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		copperarmorandtools: Copper Armor & Tools 1.4.5
		cryingportals-fabric: Crying Portals (Fabric) 1.0
		enhancedcelestials: Enhanced Celestials 2.0.6
		fabric: Fabric API 0.43.1+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd14
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.5+3ac43d9514
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+3ac43d9514
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9514
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9514
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd14
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c614
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d14
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9514
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d2957114
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a14
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.15+3ac43d9514
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.5+b4f4f6cd14
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9514
		fabric-item-api-v1: Fabric Item API (v1) 1.2.7+3ac43d9514
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9514
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f314
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd14
		fabric-language-kotlin: Fabric Language Kotlin 1.7.0+kotlin.1.6.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33514
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9514
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9514
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cd14
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9514
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9514
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd14
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.13+3ac43d9514
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.7+3ac43d9514
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac14
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d9514
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d9514
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d9514
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd14
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.3+d154e2c614
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9514
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd14
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a14
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9514
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9514
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9514
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a714
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9514
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9514
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f5514
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.4+b4f4f6cd14
		fabricloader: Fabric Loader 0.12.8
		fiber: fiber 0.23.0-2
		friendsandfoes: Friends&Foes 1.0.0
		geckolib3: Geckolib 3.0.21
		graveyard: The Graveyard 1.0
		indium: Indium 1.0.2-alpha1+mc1.18
		inventoryhud: Inventory HUD + 3.4.1
		iris: Iris 1.1.3
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kambrik: Kambrik 3.0.0
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		lambdabettergrass: LambdaBetterGrass 1.2.1+1.17
		levelz: LevelZ 1.1.1
		libgui: LibGui 5.0.0-beta.2+1.18-rc1
		libninepatch: LibNinePatch 1.1.0
		medievalorigins: Medieval Origins 3.0.2
		minecraft: Minecraft 1.18
		modmenu: Mod Menu 3.0.0
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		origins: Origins 1.2.0
		origins-classes: Origins: Classes 1.2.3
		pehkui: Pehkui 3.0.0+1.14.4-1.18
		playerabilitylib: Pal 1.3.0
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reeses-sodium-options: Reese's Sodium Options 1.2.3
		seedfix: Seed Fix 1.0.0
		skeletonhorsespawn-fabric: Skeleton Horse Spawn (Fabric) 1.9
		skinlayers: 3d Skin Layers 1.3.1
		sodium: Sodium 0.4.0-alpha5+build.9
		sodium-extra: Sodium Extra 0.3.7
		spark: spark 1.6.3
		spruceui: SpruceUI 3.3.0+1.17
		terralith: Terralith for Fabric 2.0_b0.1.8
		treeharvester-fabric: Tree Harvester (Fabric) 4.1
		villagebellrecipe-fabric: Village Bell Recipe (Fabric) 1.3
		villagernames-fabric: Villager Names (Fabric) 3.5
		villagespawnpoint-fabric: Village Spawn Point (Fabric) 1.8
		waystones: Waystones 2.3.1
		xaerominimap: Xaero's Minimap 21.22.3
		xaeroworldmap: Xaero's World Map 1.18.4
	Launched Version: fabric-loader-0.12.8-1.18
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 3.2.0 NVIDIA 497.09, NVIDIA Corporation
	Window size: 1910x1048
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/MedievalMusic.zip, file/MedievalMusic2.zip, lambdabettergrass/default (incompatible)
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz`

**Comment by Globox1997** [comment]
What I know right now it is an incompatibility with the origins mod, currently trying to contact the dev

**Comment by Globox1997** [comment]
We couldn't figure out what causes this issue exactly, so this will stay open until it gets fixed somehow

**Comment by cactusdoodad** [comment]
I think it's a Cardinal Components Issue?

**Comment by Urkaz** [comment]
I don't know if this is the same crash, but I'm having it when I create a new Singleplayer game with both mods intalled (levelz 1.1.1 and origins 1.2.0).

https://pastebin.com/ivp3jvsH

---

Just in case this helps, I noticed that this crash is **not happening** if in addition to LevelZ and Origins, you also have installed AdventureZ.

**Comment by Globox1997** [comment]
Looks like the same bug but it's super odd that it doesn't happen when another mod is installed

**Comment by Globox1997** [comment]
Should be fixed with [https://github.com/Globox1997/LevelZ/commit/0e84d9e680017fa1d18beb493620aecf789c891d](https://github.com/Globox1997/LevelZ/commit/0e84d9e680017fa1d18beb493620aecf789c891d)
