### ISSUE TITLE
[1.18.1] Crash when attempting to craft Blast Furnace

### ISSUE THREAD

**Issue by CaiganMythFang** [Globox1997/LevelZ#82]
LevelZ Version : 1.1.4

Crashing when attempting to craft a Blast Furnace. Crash happens when the mouse hovers over the 'output' of the Crafting Table. (Not when looking at recipe in REI). Item name is broken and showing what appears to be the lang file name.

Tested without LevelZ, can see item name and craft it normally.

Short part of crash log, full crash log attached.

```
Description: Rendering screen

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at net.levelz.stats.PlayerStatsManager.playerLevelisHighEnough(PlayerStatsManager.java:210)
	at net.minecraft.class_1799.handler$dki000$getTooltipMixin(class_1799.java:11203)
	at net.minecraft.class_1799.method_7950(class_1799.java:675)
	at net.minecraft.class_437.method_25408(class_437.java:182)
	at net.minecraft.class_437.method_25409(class_437.java:169)
	at net.minecraft.class_465.method_2380(class_465.java:190)
	at net.minecraft.class_479.method_25394(class_479.java:68)
	at net.minecraft.class_757.redirect$dfd000$onRenderCurrentScreen(class_757.java:7029)
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

[crash-2022-01-02_14.01.55-client.txt](https://github.com/Globox1997/LevelZ/files/7799714/crash-2022-01-02_14.01.55-client.txt)

**Comment by CaiganMythFang** [comment]
Looking through the blocks locked in /data/levelz/block/, it appears the Smithing Table and Enchanting Table as well have broken names and crash you when you attempt to craft them.

As well, if you have the item in your inventory, whether from breaking one you found in world and picking it up or otherwise (like me testing crafting with levelz disabled), if you hover your mouse over the item, it crashes you as well.

**Comment by CaiganMythFang** [comment]
Further digging, and I found out what the problem is. 

In the block lock files (data/levelz/block/), the blocks that crash are named incorrectly.  Blast Furnace example : 
`    "block": "minecraft:blastfurnace"`

That is not spelled correctly. It should be : 
`    "block": "minecraft:blast_furnace"`

Enchanting table : 
`    "block": "minecraft:enchanting",`

Should be 
`    "block": "minecraft:enchanting_table",`

And smithing table should be : 
`    "block": "minecraft:smithing_table"`

It's very interesting that the block ID's being wrong breaks the item, especially with the Blast Furnace, since the missing underscore is in the middle of the item ID.

Thankfully this looks to be a relatively easy fix to stop it crashing. I've implemented it in a datapack for my modpack and it works just fine.

**Comment by Globox1997** [comment]
This crash should only happen with a custom datapack, right?
I merged this PR [https://github.com/Globox1997/LevelZ/pull/73](https://github.com/Globox1997/LevelZ/pull/73) which changed a few names and yes they have to be correct otherwise it won't get read.

**Comment by CaiganMythFang** [comment]
Aha I see what happened, this is an error on my side.

I forgot the mod updated on the 31st and to check if the files were already fixed. I still had the data files extracted from 1.1.3 for the modpack to customize the unlocks.

My apologies!
